// Autogenerated file
// Do not manually modify
// file:../main/react/reactdatabase.c


#include <stdio.h>
#include <stdlib.h>

#include "reactdatabase.h"


const extern uint8_t dat_27__1ff2395a__chunk__js[];
const extern size_t dat_27__1ff2395a__chunk__js_size;
const extern uint8_t dat_833__d09d77f3333ed62e40d7__gif[];
const extern size_t dat_833__d09d77f3333ed62e40d7__gif_size;
const extern uint8_t dat_asset__manifest__json[];
const extern size_t dat_asset__manifest__json_size;
const extern uint8_t dat_favicon__ico[];
const extern size_t dat_favicon__ico_size;
const extern uint8_t dat_index__html[];
const extern size_t dat_index__html_size;
const extern uint8_t dat_liblouisreact__wasm[];
const extern size_t dat_liblouisreact__wasm_size;
const extern uint8_t dat_logo192__png[];
const extern size_t dat_logo192__png_size;
const extern uint8_t dat_logo512__png[];
const extern size_t dat_logo512__png_size;
const extern uint8_t dat_main__389c5937__css[];
const extern size_t dat_main__389c5937__css_size;
const extern uint8_t dat_main__7bb60419__js[];
const extern size_t dat_main__7bb60419__js_size;
const extern uint8_t dat_main__7bb60419__js__LICENSE__txt[];
const extern size_t dat_main__7bb60419__js__LICENSE__txt_size;
const extern uint8_t dat_manifest__json[];
const extern size_t dat_manifest__json_size;
const extern uint8_t dat_robots__txt[];
const extern size_t dat_robots__txt_size;
react_database react_datafiles[] = {
	{ "27.1ff2395a.chunk.js",dat_27__1ff2395a__chunk__js, &dat_27__1ff2395a__chunk__js_size },
	{ "833.d09d77f3333ed62e40d7.gif",dat_833__d09d77f3333ed62e40d7__gif, &dat_833__d09d77f3333ed62e40d7__gif_size },
	{ "asset-manifest.json",dat_asset__manifest__json, &dat_asset__manifest__json_size },
	{ "favicon.ico",dat_favicon__ico, &dat_favicon__ico_size },
	{ "index.html",dat_index__html, &dat_index__html_size },
	{ "liblouisreact.wasm",dat_liblouisreact__wasm, &dat_liblouisreact__wasm_size },
	{ "logo192.png",dat_logo192__png, &dat_logo192__png_size },
	{ "logo512.png",dat_logo512__png, &dat_logo512__png_size },
	{ "main.389c5937.css",dat_main__389c5937__css, &dat_main__389c5937__css_size },
	{ "main.7bb60419.js",dat_main__7bb60419__js, &dat_main__7bb60419__js_size },
	{ "main.7bb60419.js.LICENSE.txt",dat_main__7bb60419__js__LICENSE__txt, &dat_main__7bb60419__js__LICENSE__txt_size },
	{ "manifest.json",dat_manifest__json, &dat_manifest__json_size },
	{ "robots.txt",dat_robots__txt, &dat_robots__txt_size },
};


react_database_info react_datafiles_info[] = {
	{ "27.1ff2395a.chunk.js","/static/js/27.1ff2395a.chunk.js","text/plain"  },
	{ "833.d09d77f3333ed62e40d7.gif","/static/media/833.d09d77f3333ed62e40d7.gif","image/gif"  },
	{ "asset-manifest.json","/asset-manifest.json","application/json"  },
	{ "favicon.ico","/favicon.ico","image/x-icon"  },
	{ "index.html","/index.html","text/html"  },
	{ "liblouisreact.wasm","/liblouisreact.wasm","application/wasm"  },
	{ "logo192.png","/logo192.png","image/png"  },
	{ "logo512.png","/logo512.png","image/png"  },
	{ "main.389c5937.css","/static/css/main.389c5937.css","text/css"  },
	{ "main.7bb60419.js","/static/js/main.7bb60419.js","text/plain"  },
	{ "main.7bb60419.js.LICENSE.txt","/static/js/main.7bb60419.js.LICENSE.txt","text/plain"  },
	{ "manifest.json","/manifest.json","application/json"  },
	{ "robots.txt","/robots.txt","text/plain"  },
};


