// Autogenerated file
// Do not manually modify
// file:../main/react/reactdatabase.h



#ifndef	__REACTDATABASE_H_H
#define	__REACTDATABASE_H_H


#define	REACT_DATABASE_NBR	19
#define	REACT_DATAFILES_INFO_NBR	19


typedef struct _react_database{
	const char *fname;
	const uint8_t* data;
	const size_t* size;
} react_database;


typedef struct _react_database_info{
	const char     *fname;
	const char     *path;
	const char     *mime_type;
} react_database_info;
#endif


