// Autogenerated file
// Do not manually modify
// file:../main/react/reactdatabase.c


#include <stdio.h>
#include <stdlib.h>

#include "reactdatabase.h"


const extern uint8_t dat_27__54de6876__chunk__js[];
const extern size_t dat_27__54de6876__chunk__js_size;
const extern uint8_t dat_833__d09d77f3333ed62e40d7__gif[];
const extern size_t dat_833__d09d77f3333ed62e40d7__gif_size;
const extern uint8_t dat_asset__manifest__json[];
const extern size_t dat_asset__manifest__json_size;
const extern uint8_t dat_favicon__16x16__ico[];
const extern size_t dat_favicon__16x16__ico_size;
const extern uint8_t dat_favicon__16x16__png[];
const extern size_t dat_favicon__16x16__png_size;
const extern uint8_t dat_favicon__32x32__ico[];
const extern size_t dat_favicon__32x32__ico_size;
const extern uint8_t dat_favicon__32x32__png[];
const extern size_t dat_favicon__32x32__png_size;
const extern uint8_t dat_favicon__64x64__png[];
const extern size_t dat_favicon__64x64__png_size;
const extern uint8_t dat_favicon__ico[];
const extern size_t dat_favicon__ico_size;
const extern uint8_t dat_index__html[];
const extern size_t dat_index__html_size;
const extern uint8_t dat_liblouisreact__wasm[];
const extern size_t dat_liblouisreact__wasm_size;
const extern uint8_t dat_logo192__png[];
const extern size_t dat_logo192__png_size;
const extern uint8_t dat_logo512__png[];
const extern size_t dat_logo512__png_size;
const extern uint8_t dat_main__1125308c__js[];
const extern size_t dat_main__1125308c__js_size;
const extern uint8_t dat_main__1125308c__js__LICENSE__txt[];
const extern size_t dat_main__1125308c__js__LICENSE__txt_size;
const extern uint8_t dat_main__ec9eda20__css[];
const extern size_t dat_main__ec9eda20__css_size;
const extern uint8_t dat_manifest__json[];
const extern size_t dat_manifest__json_size;
const extern uint8_t dat_menu__91defac14b44e31b3c4ee5cdc686b0a4__svg[];
const extern size_t dat_menu__91defac14b44e31b3c4ee5cdc686b0a4__svg_size;
const extern uint8_t dat_robots__txt[];
const extern size_t dat_robots__txt_size;
react_database react_datafiles[] = {
	{ "27.54de6876.chunk.js",dat_27__54de6876__chunk__js, &dat_27__54de6876__chunk__js_size },
	{ "833.d09d77f3333ed62e40d7.gif",dat_833__d09d77f3333ed62e40d7__gif, &dat_833__d09d77f3333ed62e40d7__gif_size },
	{ "asset-manifest.json",dat_asset__manifest__json, &dat_asset__manifest__json_size },
	{ "favicon-16x16.ico",dat_favicon__16x16__ico, &dat_favicon__16x16__ico_size },
	{ "favicon-16x16.png",dat_favicon__16x16__png, &dat_favicon__16x16__png_size },
	{ "favicon-32x32.ico",dat_favicon__32x32__ico, &dat_favicon__32x32__ico_size },
	{ "favicon-32x32.png",dat_favicon__32x32__png, &dat_favicon__32x32__png_size },
	{ "favicon-64x64.png",dat_favicon__64x64__png, &dat_favicon__64x64__png_size },
	{ "favicon.ico",dat_favicon__ico, &dat_favicon__ico_size },
	{ "index.html",dat_index__html, &dat_index__html_size },
	{ "liblouisreact.wasm",dat_liblouisreact__wasm, &dat_liblouisreact__wasm_size },
	{ "logo192.png",dat_logo192__png, &dat_logo192__png_size },
	{ "logo512.png",dat_logo512__png, &dat_logo512__png_size },
	{ "main.1125308c.js",dat_main__1125308c__js, &dat_main__1125308c__js_size },
	{ "main.1125308c.js.LICENSE.txt",dat_main__1125308c__js__LICENSE__txt, &dat_main__1125308c__js__LICENSE__txt_size },
	{ "main.ec9eda20.css",dat_main__ec9eda20__css, &dat_main__ec9eda20__css_size },
	{ "manifest.json",dat_manifest__json, &dat_manifest__json_size },
	{ "menu.91defac14b44e31b3c4ee5cdc686b0a4.svg",dat_menu__91defac14b44e31b3c4ee5cdc686b0a4__svg, &dat_menu__91defac14b44e31b3c4ee5cdc686b0a4__svg_size },
	{ "robots.txt",dat_robots__txt, &dat_robots__txt_size },
};


react_database_info react_datafiles_info[] = {
	{ "27.54de6876.chunk.js","/static/js/27.54de6876.chunk.js","text/plain"  },
	{ "833.d09d77f3333ed62e40d7.gif","/static/media/833.d09d77f3333ed62e40d7.gif","image/gif"  },
	{ "asset-manifest.json","/asset-manifest.json","application/json"  },
	{ "favicon-16x16.ico","/favicon-16x16.ico","image/x-icon"  },
	{ "favicon-16x16.png","/favicon-16x16.png","image/png"  },
	{ "favicon-32x32.ico","/favicon-32x32.ico","image/x-icon"  },
	{ "favicon-32x32.png","/favicon-32x32.png","image/png"  },
	{ "favicon-64x64.png","/favicon-64x64.png","image/png"  },
	{ "favicon.ico","/favicon.ico","image/x-icon"  },
	{ "index.html","/index.html","text/html"  },
	{ "liblouisreact.wasm","/liblouisreact.wasm","application/wasm"  },
	{ "logo192.png","/logo192.png","image/png"  },
	{ "logo512.png","/logo512.png","image/png"  },
	{ "main.1125308c.js","/static/js/main.1125308c.js","text/plain"  },
	{ "main.1125308c.js.LICENSE.txt","/static/js/main.1125308c.js.LICENSE.txt","text/plain"  },
	{ "main.ec9eda20.css","/static/css/main.ec9eda20.css","text/css"  },
	{ "manifest.json","/manifest.json","application/json"  },
	{ "menu.91defac14b44e31b3c4ee5cdc686b0a4.svg","/static/media/menu.91defac14b44e31b3c4ee5cdc686b0a4.svg","image/svg+xml"  },
	{ "robots.txt","/robots.txt","text/plain"  },
};


