// Autogenerated file
// Do not manually modify
// file:../main/react/reactdatabase.c


#include <stdio.h>
#include <stdlib.h>

#include "reactdatabase.h"


const extern uint8_t dat_787__53b49820__chunk__js[];
const extern size_t dat_787__53b49820__chunk__js_size;
const extern uint8_t dat_787__53b49820__chunk__js__map[];
const extern size_t dat_787__53b49820__chunk__js__map_size;
const extern uint8_t dat_asset__manifest__json[];
const extern size_t dat_asset__manifest__json_size;
const extern uint8_t dat_favicon__ico[];
const extern size_t dat_favicon__ico_size;
const extern uint8_t dat_index__html[];
const extern size_t dat_index__html_size;
const extern uint8_t dat_logo192__png[];
const extern size_t dat_logo192__png_size;
const extern uint8_t dat_logo512__png[];
const extern size_t dat_logo512__png_size;
const extern uint8_t dat_main__a99256c7__js[];
const extern size_t dat_main__a99256c7__js_size;
const extern uint8_t dat_main__a99256c7__js__LICENSE__txt[];
const extern size_t dat_main__a99256c7__js__LICENSE__txt_size;
const extern uint8_t dat_main__a99256c7__js__map[];
const extern size_t dat_main__a99256c7__js__map_size;
const extern uint8_t dat_main__cee90dbd__css[];
const extern size_t dat_main__cee90dbd__css_size;
const extern uint8_t dat_main__cee90dbd__css__map[];
const extern size_t dat_main__cee90dbd__css__map_size;
const extern uint8_t dat_manifest__json[];
const extern size_t dat_manifest__json_size;
const extern uint8_t dat_robots__txt[];
const extern size_t dat_robots__txt_size;
react_database react_datafiles[] = {
	{ "787.53b49820.chunk.js",dat_787__53b49820__chunk__js, &dat_787__53b49820__chunk__js_size },
	{ "787.53b49820.chunk.js.map",dat_787__53b49820__chunk__js__map, &dat_787__53b49820__chunk__js__map_size },
	{ "asset-manifest.json",dat_asset__manifest__json, &dat_asset__manifest__json_size },
	{ "favicon.ico",dat_favicon__ico, &dat_favicon__ico_size },
	{ "index.html",dat_index__html, &dat_index__html_size },
	{ "logo192.png",dat_logo192__png, &dat_logo192__png_size },
	{ "logo512.png",dat_logo512__png, &dat_logo512__png_size },
	{ "main.a99256c7.js",dat_main__a99256c7__js, &dat_main__a99256c7__js_size },
	{ "main.a99256c7.js.LICENSE.txt",dat_main__a99256c7__js__LICENSE__txt, &dat_main__a99256c7__js__LICENSE__txt_size },
	{ "main.a99256c7.js.map",dat_main__a99256c7__js__map, &dat_main__a99256c7__js__map_size },
	{ "main.cee90dbd.css",dat_main__cee90dbd__css, &dat_main__cee90dbd__css_size },
	{ "main.cee90dbd.css.map",dat_main__cee90dbd__css__map, &dat_main__cee90dbd__css__map_size },
	{ "manifest.json",dat_manifest__json, &dat_manifest__json_size },
	{ "robots.txt",dat_robots__txt, &dat_robots__txt_size },
};


react_database_info react_datafiles_info[] = {
	{ "787.53b49820.chunk.js","/static/js/787.53b49820.chunk.js","text/plain"  },
	{ "787.53b49820.chunk.js.map","/static/js/787.53b49820.chunk.js.map","text/plain"  },
	{ "asset-manifest.json","/asset-manifest.json","application/json"  },
	{ "favicon.ico","/favicon.ico","image/x-icon"  },
	{ "index.html","/index.html","text/html"  },
	{ "logo192.png","/logo192.png","image/png"  },
	{ "logo512.png","/logo512.png","image/png"  },
	{ "main.a99256c7.js","/static/js/main.a99256c7.js","text/plain"  },
	{ "main.a99256c7.js.LICENSE.txt","/static/js/main.a99256c7.js.LICENSE.txt","text/plain"  },
	{ "main.a99256c7.js.map","/static/js/main.a99256c7.js.map","text/plain"  },
	{ "main.cee90dbd.css","/static/css/main.cee90dbd.css","text/css"  },
	{ "main.cee90dbd.css.map","/static/css/main.cee90dbd.css.map","text/plain"  },
	{ "manifest.json","/manifest.json","application/json"  },
	{ "robots.txt","/robots.txt","text/plain"  },
};


